let main = document.createElement('main')
let header = document.createElement('h1')
header.append('Generic Title')
let wholeBody = document.querySelector('body')
wholeBody.append(header)
wholeBody.append(main)
let section = document.createElement('section')
main.append(section)
let header2 = document.createElement('h2')
header2.append('Generic Title Number 2')
section.append(header2)
let paragraph = document.createElement('p')
paragraph.append('Here is some random text.')
main.append(paragraph)
let bigList = document.createElement('ul')
for(let i = 0; i < 6; i++){
    let l = document.createElement('li')
    l.append(`This is item ${i}`)
    bigList.append(l)
}
main.append(bigList)